#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_INPUT_CWSTM32)	+= CwMcuSensor/

